Repository SOPT-server/NOW-SOPT-effective-java, pull requests merged in 2024-05, with the labels that each got.

#18 [유난] 3주차
  unan/week3/유난-3주차_아이템10_equals는_일반_규약을_지켜_재정의하라.md
  unan/week3/유난-3주차_아이템11_equals를_재정의하려거든_hashCode도_재정의하라.md
  unan/week3/유난-3주차_아이템12_toString을_항상_재정의하라.md
  unan/week3/유난-3주차_아이템13_clone_재정의는_주의해서_진행하라.md
  unan/week3/유난-3주차_아이템9_try-finally_보다는_try-with-resource를_사용하라.md
Labels: 🐻유난🐻

#21 영린 - 3주차
  0lynny/week3/영린-3주차-아이템10_equals는_일반_규약을_지켜_ 재정의하라.md
  0lynny/week3/영린-3주차-아이템11_equals를_재정의하려거든_ hashCode도_재정의하라.md
  0lynny/week3/영린-3주차-아이템12_toString을_항상_재정의하라.md
  0lynny/week3/영린-3주차-아이템13_clone재정의는_주의해서_진행해라.md
  0lynny/week3/영린-3주차-아이템9_try-finally보다는_try-with-resources를_사용하라.md
Labels: 🐨영란🐨

#24 보람 - 3주차
  boram/week3/보람-3주차-아이템10_equals는_일반_규약을_지켜_재정의하라.md
  boram/week3/보람-3주차-아이템11_equals를_재정의하려거든_hashCode도_재정의하라.md
  boram/week3/보람-3주차-아이템12_toString을_항상_재정의하라.md
  boram/week3/보람-3주차-아이템13.clone_재정의는_주의해서_진행하라.md
  boram/week3/보람-3주차-아이템9_try-finally보다는_try-with-resources를_사용하라.md
Labels: 👻람보👻

#25 유난-4주차
  unan/week4/유난-4주차_아이템14_Comparable을_어떻게_구현할지_고려하라.md
  unan/week4/유난-4주차_아이템15_클래스와_멤버의_접근_제한자를_최소화하라.md
  unan/week4/유난-4주차_아이템16_public_class에서는_public필드가_아닌_접근자_method를 사용하라.md
  unan/week4/유난-4주차_아이템17_변경_가능성을_최소화하라.md
Labels: 🐻유난🐻

#27 보람-4주차
  boram/week4/보람-4주차-아이템14_Comparable을_구현할지_고려하라.md
  boram/week4/보람-4주차-아이템15_클래스와_멤버의_접근_권한을_최소화하라.md
  boram/week4/보람-4주차-아이템16_public_클래스에서는_public_필드가_아닌_접근자_메서드를_사용하라.md
  boram/week4/보람-4주차-아이템17_변경_가능성을_최소화하라.md
Labels: 👻람보👻

#23 상준 - 3주차
  sangjune/3주차/상준-3주차-아이템10_equals는_일반_규약을_지켜_ 재정의하라.md
  sangjune/3주차/상준-3주차-아이템11_equals를_재정의하려거든_ hashCode도_재정의하라.md
  sangjune/3주차/상준-3주차-아이템12_toString을_항상_재정의하라.md
  sangjune/3주차/상준-3주차-아이템9_try-finally보다는_try-with-resources를_사용하라.md
Labels: 🐈동박🐈

#26 상준 - 4주차
  sangjune/4주차/상준-4주차_아이템14_Comparable을_구현할지_고려하라.md
  sangjune/4주차/상준-4주차_아이템15_클래스와_멤버의_접근_제한자를_최소화하라.md
  sangjune/4주차/상준-4주차_아이템16_public_class에서는_public필드가_아닌_접근자_method를 사용하라.md
  sangjune/4주차/상준-4주차_아이템17_변경_가능성을_최소화하라.md
Labels: 🐈동박🐈

#29 태욱 - 3주차
  wooki/week3/item09.md
  wooki/week3/item10.md
  wooki/week3/item11.md
  wooki/week3/item12.md
Labels: 🐼욱짱🐼
