Repository SOPT-server/NOW-SOPT-effective-java, pull requests merged in 2024-04, with the labels that each got.

#1 유난-1주차
  unan/week1/유난-1주차-아이템1_생성자_대신_정적_팩토리_메소드를_고려하라.md
  unan/week1/유난-1주차-아이템2_생성자에_매개변수가_많다면_빌더를_고려해라.md
  unan/week1/유난-1주차-아이템3_private과_Enum으로_싱글톤을_보증하라.md
  unan/week1/유난-1주차_아이템4_인스턴스화를_막기_위해서_private를_사용하자.md
Labels: 🐻유난🐻

#4 소현 - 1주차
  sohyun/week1/소현-1주차-아이템1_생성자_대신_정적_팩토리_메소드를_고려하라.md
  sohyun/week1/소현-1주차-아이템2_생성자에_매개변수가_많다면_빌더를_고려하라.md
  sohyun/week1/소현-1주차-아이템3_private과_Enum으로_싱글톤을_보증하라.md
  sohyun/week1/소현-1주차_아이템4_인스턴스화를_막기_위해서_private를_사용하자.md
Labels: 🐦도도🐦

#5 보람 - 1주차
  boram/week1/boram/week1/보람-1주차-아이템1_생성자_대신_정적_팩터리_메소드를_고려하라.md
  boram/week1/boram/week1/보람-1주차-아이템2_생성자에_매개변수가_많다면_빌더를_고려해라.md
  boram/week1/boram/week1/보람-1주차-아이템3_아이템3_private과_Enum으로_싱글톤을_보증하라.md
  boram/week1/boram/week1/보람-1주차-아이템4_인스턴스화를_막기_위해서_private를_사용하자.md
Labels: 👻람보👻

#6 영린 - 1주차
  0lynny/week1/영린-1주차-아이템1_생성자_대신_정적_팩토리_메소드를_고려하라.md
  0lynny/week1/영린-1주차-아이템2_생성자에_매개변수가_많다면_빌더를_고려하라.md
  0lynny/week1/영린-1주차-아이템3_private과_Enum으로_싱글턴임을_보증하라.md
  0lynny/week1/영린-1주차-아이템4_인스턴스화를_막으려거든_private생성자를_사용하라..md
Labels: 🐨영란🐨

#7 상준 - 1주차
  sangjune/1주차/상준-1주차-아이템1_생성자_대신_정적_팩토리_메소드를_고려하라.md
  sangjune/1주차/상준-1주차-아이템2_생성자에_매개변수가_많다면_빌더를_고려하라.md
  sangjune/1주차/상준-1주차-아이템3_private_생성자나_열거_타입으로_싱글턴임을_보증하라.md
  sangjune/1주차/상준-1주차-아이템4_인스턴스화를_막으려거든_private_생성자를_사용하라.md
Labels: 🐈동박🐈

#9 태욱 - 1주차
  wooki/week1/item01.md
  wooki/week1/item02.md
  wooki/week1/item03.md
  wooki/week1/item04.md
Labels: 🐼욱짱🐼

#10 정원 - 1주차
  garden/week1/정원-1주차-아이템1_생성자_대신_정적_팩토리_메소드를_고려하라.md
  garden/week1/정원-1주차-아이템2_생성자에_매개변수가_많다면_빌더를_고려하라.md
  garden/week1/정원-1주차-아이템3_private_생성자나_열거_타입으로_싱글턴임을_보증하라.md
  garden/week1/정원-1주차-아이템4_인스턴스화를_막으려거든_private_생성자를_사용하라.md
Labels: 🐹가든🐹

#14 유난 - 2주차
  unan/week2/유난-2주차_아이템5_자원을_직접_명시하지_말고_의존_객체_주입을_사용하라.md
  unan/week2/유난-2주차_아이템6_불필요한_객체_생성을_피하라.md
  unan/week2/유난-2주차_아이템7_다_쓴_객체_참조를_해제하라.md
  unan/week2/유난-2주차_아이템8_finalizer_cleaner_사용을_피하라.md
Labels: 🐻유난🐻

#15 영린 - 2주차
  0lynny/week2/영린-2주차-아이템5_자원을_직접_명시하지_말고_의존_객체_주입을_사용하라.md
  0lynny/week2/영린-2주차-아이템6_불필요한_객체_생성을_피하라.md
  0lynny/week2/영린-2주차-아이템7_다_쓴_객체_참조를_해제하라.md
  0lynny/week2/영린-2주차-아이템8_finalizer와_cleaner_사용을_피하라.md
Labels: 🐨영란🐨

#16 소현 - 2주차
  sohyun/week2/소현-2주차_아이템5_자원을_직접_명시하지_말고_의존_객체_주입을_사용하라.md
  sohyun/week2/소현-2주차_아이템6_불필요한_객체_생성을_피하라.md
  sohyun/week2/소현-2주차_아이템7_다_쓴_객체_참조를_해제하라.md
  sohyun/week2/소현-2주차_아이템8_finalizer_cleaner_사용을_피하라.md
Labels: 🐦도도🐦

#17 보람 - 2주차
  boram/week2/보람-2주차-아이템5_자원을_직접_명시하지_말고_의존_객체_주입을_사용하라.md
  boram/week2/보람-2주차-아이템6_불필요한_객체_생성을_피하라.md
  boram/week2/보람-2주차-아이템7_다_쓴_객체_참조를_해제하라.md
  boram/week2/보람-2주차-아이템8_finalizer과_cleaner_사용을_피하라.md
Labels: 👻람보👻

#19 태욱 - 2주차
  wooki/week2/item05.md
  wooki/week2/item06.md
  wooki/week2/item07.md
  wooki/week2/item08.md
Labels: 🐼욱짱🐼

#20 정원 - 2주차
  garden/week2/정원-2주차-아이템5_자원을_직접_명시하지_말고_의존_객체_주입을_사용하라.md
  garden/week2/정원-2주차-아이템6_ 불필요한_객체_생성을_피하라.md
  garden/week2/정원-2주차-아이템7_다_쓴_객체_참조를_해제하라.md
  garden/week2/정원-2주차-아이템8_finalizer와_cleaner_사용을_피하라.md
Labels: 🐹가든🐹
