Repository SOPT-server/NOW-SOPT-effective-java, pull requests merged in 2024-06, with the labels that each got.

#36 태욱 - 6주차
  wooki/week6/item21.md
  wooki/week6/item22.md
  wooki/week6/item23.md
Labels: 🐼욱짱🐼

#37 영린 - 6주차
  0lynny/week6/영린-6주차-아이템21_인터페이스는_구현하는_쪽을_생각해_설계하라md.md
  0lynny/week6/영린-6주차-아이템22_인터페이스는_구현하는_쪽을_생각해_설계하라.md
  0lynny/week6/영린-6주차-아이템23_태그_달린_클래스보다는_클래스_계층구조를_활용하라.md
Labels: 🐨영란🐨

#28 유난 - 5주차
  unan/week5/유난-5주차_아이템18_상속보다는컴포지션을사용하라.md
  unan/week5/유난-5주차_아이템19_상속을_고려해_설계하고문서화하라_그러지_않았다면_상속을_금지하라.md
  unan/week5/유난-5주차_아이템20_추상_클래스보다는_인터페이스를_우선하라.md
Labels: 🐻유난🐻

#31 보람 - 5주차
  boram/week5/보람-5주차-아이템18_상속보다는_컴포지션을_사용하라.md
  boram/week5/보람-5주차-아이템19_상속을_고려해_설계하고_문서화하라.그러지않았다면_상속을_금지하라.md
  boram/week5/보람-5주차-아이템20_추상클래스보다는_인터페이스를_우선하라.md
Labels: 👻람보👻

#32 소현-5주차
  sohyun/week5/소현-5주차_아이템18_상속보다는_컴포지션을_사용하라.md
  sohyun/week5/소현-5주차_아이템19_상속을_고려해_설계하고문서화하라_그러지_않았다면_상속을_금지하라.md
  sohyun/week5/소현-5주차_아이템20_추상_클래스보다는_인터페이스를_우선하라.md
Labels: 🐦도도🐦

#33 정원 - 5주차
  garden/week3/정원-3주차-아이템9_try-finally보다는_try-with-resources를_사용하라.md
  garden/week5/정원-5주차-아이템18_상속보다는_컴포지션을_사용하라.md
  garden/week5/정원-5주차-아이템19_상속을_고려해_설계하고_문서화하라._그러지_않았다면_상속을_금지하라.md
  garden/week5/정원-5주차-아이템20_추상_클래스보다는_인터페이스를_우선하라.md
Labels: 🐹가든🐹

#22 정원 - 3주차
  garden/week3/정원-3주차-아이템9_try-finally보다는_try-with-resources를_사용하라.md
Labels: 🐹가든🐹

#34 상준 - 5주차
  sangjune/5주차/상준-5주차-아이템18_상속보다는_컴포지션을_사용하라 copy.md
  sangjune/5주차/상준-5주차-아이템19_상속을_고려해_설계하고_문서화하라 _그러지_않았다면 상속을 금지하라.md
  sangjune/5주차/상준-5주차-아이템20_추상_클래스보다는_인터페이스를_선호하라.md
Labels: 🐈동박🐈

#39 영린 - 7주차
  0lynny/week7/영린-7주차-아이템24_멤버클래스는_되도록_Static으로 _만들라.md
  0lynny/week7/영린-7주차-아이템25_톱레벨_클래스는_한_파일에_하나만_담으라.md
  0lynny/week7/영린-7주차-아이템26_로타입은_사용하지_마라.md
Labels: 🐨영란🐨
